version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: ./backend
    container_name: pong-backend-container
    command: > 
      sh -c "
      while ! nc -z database 5432; do 
        echo 'Waiting for db...';
        sleep 1; 
      done; 
      echo 'Db is up, running migrations...';
      python3 api/manage.py makemigrations && 
      python3 api/manage.py migrate && 
      echo 'Starting Daphne...';
      daphne -p 8000 api.api.asgi:application"     
    volumes:
      - ./backend:/app
      - ./backend/media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - database
      - redis
    env_file:
      - .env
    networks:
      - pong-network
    restart: on-failure

  # Database service
  database:
    build:
      context: ./database
    container_name: pong-database-container
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - pong-network

  # Frontend service
  frontend:
    build:
      context: ./frontend
    container_name: pong-frontend-container
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - pong-network
    restart: on-failure
  
  # Redis service
  redis:
    image: redis:alpine
    container_name: pong-redis-container
    ports:
      - "6379:6379"
    networks:
      - pong-network

volumes:
  postgres_data:
  media_data: 

networks:
  pong-network:
    driver: bridge

