services:
  # Backend service
  backend:
    build:
      context: ./backend
      args:
        - ACTIVE_HOST=${ACTIVE_HOST}
    container_name: pong-backend-container
    command: > 
      sh -c "
      while ! nc -z database 5432; do 
        echo 'Waiting for db...';
        sleep 1; 
      done; 
      echo 'Db is up, running migrations...';
      python3 api/manage.py makemigrations; 
      python3 api/manage.py migrate;
      python api/manage.py create_ai_user;
      echo 'Starting Daphne...';
      cd api && daphne -b 0.0.0.0 -p 8000 api.asgi:application"     
    volumes:
      - ./backend:/app # remove this line when no longer in dev
      - media:/app/api/media
    depends_on:
      - database
      - redis
    env_file:
      - .env
    networks:
      - pong-network
    restart: on-failure

  # Database service
  database:
    build:
      context: ./database
    container_name: pong-database-container
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - pong-network

  # Frontend service
  frontend:
    build:
      context: ./frontend
      args:
        - ACTIVE_HOST=${ACTIVE_HOST}
    container_name: pong-frontend-container
    volumes:
      - media:/usr/share/nginx/html/media
    ports:
      - "0.0.0.0:443:443"
    depends_on:
      - backend
    networks:
      - pong-network
    restart: on-failure
  
  # Redis service
  redis:
    image: redis:alpine
    container_name: pong-redis-container
    ports:
      - "0.0.0.0:6379:6379"
    networks:
      - pong-network

  # Vault service
  vault:
    build:
      context: ./vault
    container_name: pong-vault-container
    ports:
      - "0.0.0.0:8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root
    volumes:
      - vault_data:/vault/data
      - .vault/secrets/.env:/vault/secrets/.env
      - ./vault/init-vault.sh:/init-vault.sh
    networks:
      - pong-network
    command: "sh /init-vault.sh && vault server -dev -dev-root-token-id=root -dev-listen-address=0.0.0.0:8200"
    restart: unless-stopped

volumes:
  postgres_data:
  media:
  vault_data:

networks:
  pong-network:
    driver: bridge

