# Generated by Django 4.2.16 on 2024-09-29 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RrGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_win', models.BooleanField(default=False)),
                ('date_played', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(default=0)),
                ('opponenet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_opponent', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PongGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_win', models.BooleanField(default=False)),
                ('date_played', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(default=0)),
                ('attack1_accuracy', models.IntegerField(default=0)),
                ('attack2_accuracy', models.IntegerField(default=0)),
                ('map_name', models.TextField()),
                ('shield_powerup', models.IntegerField(default=0)),
                ('opponenet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_opponent', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
