# Generated by Django 4.2.16 on 2024-10-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PongGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(blank=True, editable=False, max_length=20)),
                ('is_win', models.BooleanField(default=False)),
                ('date_played', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(default=0)),
                ('attack_accuracy', models.IntegerField(default=0)),
                ('map_name', models.TextField()),
                ('shield_powerup', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RrGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(blank=True, editable=False, max_length=20)),
                ('is_win', models.BooleanField(default=False)),
                ('date_played', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(default=0)),
                ('average_moves', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
