# Generated by Django 4.2.16 on 2024-10-22 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rrgame',
            name='opponent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_opponent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rrgame',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ponggame',
            name='opponent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_opponent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ponggame',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='rrgame',
            unique_together={('user', 'game_id')},
        ),
        migrations.AlterUniqueTogether(
            name='ponggame',
            unique_together={('user', 'game_id')},
        ),
    ]
