# Generated by Django 4.2.16 on 2024-10-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rrgame',
            name='average_moves',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
