# Generated by Django 4.2.17 on 2024-12-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponggame',
            name='attack_powerup',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='ponggame',
            name='game_duration',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ponggame',
            name='game_mode',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ponggame',
            name='is_forfeit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ponggame',
            name='speed_powerup',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ponggame',
            name='attack_accuracy',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='ponggame',
            name='game_id',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='ponggame',
            name='shield_powerup',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.DeleteModel(
            name='RrGame',
        ),
    ]
