# Generated by Django 4.2.16 on 2024-11-18 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RrGame',
        ),
    ]
