# Generated by Django 4.2.17 on 2024-12-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_ponggame_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponggame',
            name='game_id',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
