# Generated by Django 4.2.17 on 2024-12-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_ponggame_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponggame',
            name='attack_powerup',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ponggame',
            name='game_duration',
            field=models.FloatField(default=0.0),
        ),
    ]
