# Generated by Django 4.2.17 on 2024-12-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_ponggame_attack_powerup_ponggame_game_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponggame',
            name='attack_accuracy',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='ponggame',
            name='attack_powerup',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ponggame',
            name='shield_powerup',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ponggame',
            name='speed_powerup',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
