# Generated by Django 4.2.16 on 2024-10-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='status',
            field=models.CharField(choices=[('FRIENDS', 'Friends'), ('PENDING', 'Pending'), ('BLOCKED', 'Blocked')], default='PENDING', max_length=10),
        ),
    ]
