# Generated by Django 4.2.16 on 2024-09-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
    ]
