# Generated by Django 4.2.17 on 2024-12-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_twofa_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='t_won',
            field=models.IntegerField(default=0),
        ),
    ]
